### ISSUE TITLE
Unabled to *make* [Debian 8]

### ISSUE THREAD

**Issue by ObaniGemini** [GrangerHub/tremulous#2] opened 2017-02-17 11:06 UTC
**GRANGER BRANCH**

Happends all the time in src/qcommon/common.c
`error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode`

I got also lots of error in several files saying :
`warning: comparison between signed and unsigned integer expressions [-Wsign-compare]`

Seeing the redundance of all those errors, it's probably due to a wrong c++ version. Any indications about that ?

EDIT : I would like to use clang as a build system cause gcc is outdated on Debian 8. Why do you force the use of gcc ?

EDIT : I'm dummy, gonna try something

**Comment by ObaniGemini** [comment] 2017-02-17 13:38
I erased build files and the original makefile to use cmake.

I changed `cmake_minimum_required` from **VERSION 3.5** to **VERSION 3.0.2** (my version)
in _./CMakeLists.txt_ and _./src/tools/CMakeLists.txt_

I also commented Windows and Apple related parts as they weren't used, and parts not concerning me (mumble to OFF, option(USE_RENDERER_DLOPEN "" ON)) to avoid any kind of problems.

For now everything builds fine.

**Comment by wtfbbqhax** [comment] 2017-02-17 13:39
@ObaniGemini 

The issue is the default C standard for your compiler is either c89/gnu89. This can be resolved by creating a Makefile.local in the same directory as the Makefile containing

```
CFLAGS=-std=gnu99
```

Minimum C++ standard is C++14

---

> EDIT : I would like to use clang as a build system cause GCC is outdated on Debian 8. Why do you force the use of GCC ? 

We don't, you can choose a different compiler by configuring it in the Makefile.local. 

Here is mine:
```
CC=$(LLVM)/bin/clang
CXX=$(LLVM)/bin/clang++
```
where LLVM is the path to my newer clang which I downloaded from clang.llvm.org

> Also, why don't you use CMake that would make things easier (to me at least), for errors, dependencies, and choice of the build system ?

We do offer CMake build system.

I don't understand what you are saying. Every single thing you're pointing out, we have.

**Comment by ObaniGemini** [comment] 2017-02-17 13:50
Please reread me

**Comment by ObaniGemini** [comment] 2017-02-17 14:00
> I don't understand what you are saying. Every single thing you're pointing out, we have.

And I don't get why wouldn't you get that without a documentation, none can do nothing, at least quickly. Documentation here says "do make"

**Comment by wtfbbqhax** [comment] 2017-02-17 14:01
Fair enough

**Comment by ObaniGemini** [comment] 2017-02-17 14:39
Changing CFLAGS doesn't do anything to me. I just still get the message `use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code`
But changing the flags just makes me get even more errors.

I never worked with C++ and am a newbie to code too so I don't get how this is supposed to work. Also, any way I could use llvm as a CFLAG ?

**Comment by wtfbbqhax** [comment] 2017-02-18 14:39
Delete the build directory first, the CFLAGS should fix the problem after that.

**Comment by ObaniGemini** [comment] 2017-02-18 14:47
I do that each time I redo cmake.

**Comment by wtfbbqhax** [comment] 2017-02-18 15:06
@ObaniGemini I've just pushed another branch `fix_old_gcc`, please give it a try.

I'm blowFish

**Comment by ObaniGemini** [comment] 2017-02-18 15:16
using simple make, I get lots of 
> dereferencing pointer to incomplete type search
> dereferencing pointer to incomplete type hintsp
> dereferencing pointer to incomplete type hints
> dereferencing pointer to incomplete type

Lots of warning, and lots of undeclared variables apparently.
http://pastebin.com/UUDPy3xJ

Also, I never was abled to compile your clients too.
Sending you a message on the forum.

**Comment by ObaniGemini** [comment] 2017-02-19 16:37
Using your branch and after installing lua, liblua, liblua-dev, libtolua++, libtolua++-dev, lua-curl, lua-curl-dev :

**Many** warnings and 2 errors :
> /src/qcommon/net_ip.c:360:58: error: ‘NI_NUMERICHOST’ undeclared (first use in this function) if(getnameinfo(input, inputlen, dest, destlen, NULL, 0, NI_NUMERICHOST) && destlen > 0)

> /src/qcommon/net_ip.c:1321:25: error: ‘IFF_UP’ undeclared (first use in this function) if(ifap->ifa_flags & IFF_UP)                         ^


Also, is it needed to have cmake_minimum_required(3.5) ?
I set it to 3.0.2 which is the mroe recent version I got.

**Comment by cengique** [comment] 2017-02-19 16:54
@ObaniGemini 3.5 > 3.0.2, so could be the reason for the errors. I'm able to compile it on my Gentoo Linux box. 

Those symbols also exist in the original Tremulous code. They are coming from basic system includes for TCP/IP networking: http://lxr.free-electrons.com/ident?i=IFF_UP

**Comment by ObaniGemini** [comment] 2017-02-19 16:56
Could isn't is.  We won't go further without clear answers. I already stated that earlier but no one answered

**Comment by cengique** [comment] 2017-02-19 17:11
@ObaniGemini Let's see if @wtfbbqhax /blowfish has something to say more. I have a debian system on the side, let me know if you are stuck and I can try compiling there.

**Comment by cengique** [comment] 2017-02-19 19:38
Ok, I'm getting weird errors trying to compile it on Debian: 

```
DED_CC src/qcommon/net_ip.c
src/qcommon/net_ip.c: In function ‘SearchAddrInfo’:
src/qcommon/net_ip.c:268:11: error: dereferencing pointer to incomplete type
   if(hints->ai_family == family)
           ^
src/qcommon/net_ip.c:271:16: error: dereferencing pointer to incomplete type
   hints = hints->ai_next;
```

kernel 3.16.0-4-amd64
gcc 4.9.2
make 4.0
no cmake

**Comment by ObaniGemini** [comment] 2017-02-19 20:56
@cengique : are you on testing or stable ? I'm on stable and I know outdated packages are often an issue there.
You might want to use cmake, I avoided using the Makefile as it never worked for me on tremulous :/

**Comment by cengique** [comment] 2017-02-19 23:03
@ObaniGemini My Debian is an abomination because it's mixed between stable/testing/unstable. You can customize your `/etc/apt/sources.list` so that you can pick and choose more recent versions of programs. If you want a more bleeding edge Linux, Arch, Manjaro, or Gentoo are better.

oh I didn't realize @wtfbbqhax got the Cmake to work for the client/server executables. So I installed cmake 3.7.2 and now I am getting the above `net_ip.c` error I got earlier with just `make` and also the `IFF_UP` error @ObaniGemini reported earlier. 

I am using the `-j` option to make should not make a difference in this case because header files seem to be missing.

@wtfbbqhax are we missing a networking header in the Cmake file?

**Comment by wtfbbqhax** [comment] 2017-02-20 17:57
The missing network header stuff doesn't make any sense. I've seen this reported by Code_Man before- his case magically resolved itself so I can only presume it's due to a continued `make` in an already failed/tainted build directory.

@cengique I've created a PR#6 which fixes the C standard which was originally reported, if you could be so kind as to review that.

**Comment by wtfbbqhax** [comment] 2017-02-20 19:52
Ok, nevermind i was able to reproduce the other issue. I'll fix it this evening.

**Comment by wtfbbqhax** [comment] 2017-02-21 04:50
@ObaniGemini This is fixed in the latest master commit

**Closed by wtfbbqhax** 2017-02-21 04:50 UTC

**Comment by ObaniGemini** [comment] 2017-02-25 19:12
compiled successfully with the Makefile :)
